# Generated by Django 5.1.1 on 2024-11-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_actions_app', '0002_budget_financialgoal_investmentportfolio_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
