# Generated by Django 5.1.1 on 2024-11-26 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EqualInstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('periods', models.IntegerField()),
                ('repayment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equal_installment_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
