# Generated by Django 5.1.1 on 2024-11-28 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_plans_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equalinstallmentplan',
            name='borrowed_amount',
            field=models.FloatField(max_length=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='equalinstallmentplan',
            name='interest_rate',
            field=models.FloatField(max_length=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='equalinstallmentplan',
            name='periods',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
