# Generated by Django 5.1.1 on 2024-11-28 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_plans_app', '0002_alter_equalinstallmentplan_borrowed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equalinstallmentplan',
            name='borrowed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='equalinstallmentplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
