# Generated by Django 5.1.1 on 2024-11-28 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_plans_app', '0005_alter_equalinstallmentplan_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equalinstallmentplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equalprincipleportion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
