# Generated by Django 5.1.1 on 2024-11-28 16:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayment_plans_app', '0007_rename_equalprincipleportion_equalprincipleportionplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EqualPrinciplePortionPlan',
            new_name='EqualPrincipalPortionPlan',
        ),
        migrations.CreateModel(
            name='EqualInstallmentChangeableIPPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('interest_rate_first_period', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('interest_rate_second_period', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('first_period', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('second_period', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('repayment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EqualPrincipalPortionChangeableIPPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('interest_rate_first_period', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('interest_rate_second_period', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('first_period', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('second_period', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('repayment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
